### ISSUE TITLE
Problem z kompilacją

### ISSUE THREAD

**Issue by usatek** [soneta/Samples#3]
Przy probie wczytania solucji dostaje komunikat:

> :\SonetaGeekOut\Samples-master\src\Samples\Samples.csproj : error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

>Detailed Information:
Unable to find package Soneta.Sdk. No packages exist with this id in source(s): Feed, Microsoft Visual Studio Offline Packages, nuget.org

>C:\Program Files\dotnet\sdk\2.1.604\Sdks\Soneta.Sdk\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.

Czy czasami czegoś nie brakuje w solucji?

**Comment by TomekScieplek** [comment]
A masz włączonego VPNa? Z tego, co wiem SDK nie zostało jeszcze opublikowane, więc musisz zapewnić dostęp do naszego prywatnego feeda.

**Comment by usatek** [comment]
ok, w jaki sposób mogę dostać dostęp do waszego prywatnego feeda, o ile to możliwe.

**Comment by TomekScieplek** [comment]
Oj, przepraszam - myślałem, że to ktoś z firmy :) Nadal pracujemy nad przykładami, a samo SDK jest jeszcze stabilizowane i wkrótce zostanie wydane. W razie czego SDK również jest dostępne na [tutaj](https://github.com/soneta/Soneta.MsBuild.SDK).

**Comment by usatek** [comment]
Rozumiem, nie pracuje u was:) Próbowałem tylko skompilować materiały na Geekout 2019

**Comment by gentooser** [comment]
Prosimy skompilować dzień przed konferencją, powinny być wtedy dostępne nugety.
________________________________

**Comment by usatek** [comment]
ok, w takim razie sprawdzę w środę.

**Comment by TomekScieplek** [comment]
@usatek, zarówno SDK jak i nugety zostały już opublikowane, więc kompilacja powinna się udać ;)
